batch_size: 100
epochs: 100
lr: 1e-3
weight_decay: 1e-4
val_size : 0.3
optimizer: Adam # or AdamW, SGD - NOT YET IMPLEMENTED
scheduler:
  - ReduceLROnPlateau # CosineAnnealingLR, None- NOT YET IMPLEMENTED
stopper_metric: acc # loss or acc
seed: 42
